---
- name: Ensure nginx exists
  yum:
    name: nginx
    state: present
  when: ansible_os_family == "CentOS"

- name: "ensure nginx package exists"
  copy: 
    src: "nginx.tar.gz"
    dest: "{{nginx_package_tmp_dir}}"

- name: "Config nginx"
  includes_tasks: config.yml

- name: start nginx
  service:
    name: nginx
    state: started